# Generated by Django 4.2 on 2023-04-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_preencimento', models.DateField(null=True)),
                ('nome', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
